---
title: "Long-term Fertilization and Mowing at WRC:  Bacterial Community Characterization"
author: "Ariane L. Peralta, Mario E. Muscarella, ...."
date: "Last updated on `r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
  - \usepackage{graphics}
output: 
  pdf_document:
  fig_caption: true
---

Project Description: 

## Initial Setup
```{r}
rm(list=ls())
setwd("~/GitHub/WRC_FertMowing/analyses")
se <- function(x, ...){sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))}
ci <- function(x, ...){1.96 * sd(x,na.rm = TRUE)}

# Code Dependencies
source("../bin/MothurTools.R")
require("vegan")
require("reshape")

```

## Experimental Design
```{r}
# Import Design
design <- read.delim("../data/2015_WRC_Expt_Design.txt")

```

## Microbial Data
```{r}
# Import OTU data
# Import Raw Data
WRC.bac.in <- read.delim("../data/WRC2015_Rhizosphere_Classified_genus_OTUs.txt",
                         row.names = 1)

WRC.bac.in2 <- WRC.bac.in[,-1]
WRC.bac.in2[1:5, 1:5]


# Remove OTUs with less than two occurences across all sites
WRC.bac <- WRC.bac.in2[, which(colSums(WRC.bac.in2) >= 2)]

# Make Presence Absence Matrix
WRC.bac.PA <- (WRC.bac > 0) * 1

# Make Relative Abundence Matrices
WRC.bac.REL <- WRC.bac
for(i in 1:dim(WRC.bac)[1]){
  WRC.bac.REL[i,] <- WRC.bac[i,]/sum(WRC.bac[i,])
}

# Log Transform Relative Abundances
WRC.bac.REL.log <- decostand(WRC.bac.REL, method="log")

# Import Taxonomy File
WRC.tax <- read.tax(taxonomy = 
                      "../data/WRC2015_Rhizosphere_Classified_genus_0.03.cons.taxonomy")

```

## Principal Coordinates Analysis
```{r}
# Create Distance Matrix
WRC.bac.REL.dist <- vegdist(WRC.bac.REL, method="bray")

# Principal Coordinates Analysis
WRC.bac.pcoa <- cmdscale(WRC.bac.REL.dist, k=3, eig=TRUE, add=FALSE)
  # Classical (Metric) Multidimensional Scaling; returns PCoA coordinates
  # eig=TRUE returns eigenvalues; k = # of dimensions to calculate

explainvar1 <- round(WRC.bac.pcoa$eig[1] / sum(WRC.bac.pcoa$eig), 3) * 100
explainvar2 <- round(WRC.bac.pcoa$eig[2] / sum(WRC.bac.pcoa$eig), 3) * 100
sum.eig <- sum(explainvar1, explainvar2)



```

## PCoA Plot
```{r, results=hide}
# Define Centroids and Error Bars
if(all.equal(row.names(WRC.bac.pcoa$points), as.character(design$SampleID))){
  points <- cbind(as.data.frame(WRC.bac.pcoa$points), design)
  } else {
    stop("samples do not match")
  }

L.centroids <- melt(points, id=c("Treatment", "Plant", "Location"), measure.vars = c("V1", "V2"))
centroids <- cast(L.centroids, variable ~ Treatment + Plant + Location, mean)
centroids.se <- cast(L.centroids, variable ~ Treatment + Plant + Location, se)
centroids.sd <- cast(L.centroids, variable ~ Treatment + Plant + Location, sd)

cent.dataframe <- t(data.frame(rbind(centroids[1,-1], centroids[2,-1],
                             centroids.sd[1,-1],centroids.sd[2,-1])))
colnames(cent.dataframe) <- c("V1", "V2", "V1e", "V2e")
cent.treats <- rownames(cent.dataframe)

myColors <- c("#FFF000", "#CCFF00", "#33CC33", "#000000", "#336633", "#FF9933", "blue", "red", "purple", "gray") #pick new
names(myColors) <- levels(cent.treats)
colScale <- scale_colour_manual(values = myColors)

# Define Plot Parameters
par(mar = c(5, 5.5, 1, 1) + 0.1)

plot(cent.dataframe[,1], cent.dataframe[,2], type = 'n', las = 1,
     xlim = c(-0.25, 0.4), ylim = c(-0.3, 0.2),
     xaxt = "n", xlab = "", yaxt = "n", ylab="")
arrows(x0 = cent.dataframe[,1], 
       y1 = cent.dataframe[,2] - cent.dataframe[,4], 
       y0 = cent.dataframe[,2] + cent.dataframe[,4],
       angle = 90,
       length=0.05, lwd = 2, code = 3)
arrows(y0 = cent.dataframe[,2], 
       x1 = cent.dataframe[,1] - cent.dataframe[,3], 
       x0 = cent.dataframe[,1] + cent.dataframe[,3],
       angle = 90,
       length=0.05, lwd = 2, code = 3)
points(cent.dataframe[,1], cent.dataframe[,2], 
       cex = 2.5, col = myColors, pch = 15)
legend("topright", legend = cent.treats, col = myColors, 
       pch = 15, cex = 0.75, bty = 'n', inset = c(0.1, 0.05),
       y.intersp = 1.25)

axis(side = 1, labels = T, las = 1, lwd.ticks = 2)
axis(side = 2, labels = T, las = 1, lwd.ticks = 2)
axis(side=1, lwd.ticks = 2, tck = -0.02, labels=F, cex.axis=1)
axis(side=3, lwd.ticks = 2, tck = -0.02, labels=F, cex.axis=1)
axis(side=1, lwd.ticks = 2, tck = 0.01, labels=F, cex.axis=1)
axis(side=3, lwd.ticks = 2, tck = 0.01, labels=F, cex.axis=1)
axis(side = 2, lwd.ticks = 2, tck = -0.02, labels=F, cex.axis=1)
axis(side = 4, lwd.ticks = 2, tck = -0.02, labels=F, cex.axis=1)
axis(side = 2, lwd.ticks = 2, tck = 0.01, labels=F, cex.axis=1)
axis(side = 4, lwd.ticks = 2, tck = 0.01, labels=F, cex.axis=1)

abline(h = 0, col = "gray60", lty = "dotted")
abline(v = 0, col = "gray60", lty = "dotted")

mtext(paste("PCoA 1 (", explainvar1, "%)", sep = ""), side = 1, line = 3, cex = 1.5)
mtext(paste("PCoA 2 (", explainvar2, "%)", sep = ""), side = 2, line = 3.5, cex = 1.5)
      
box(lwd = 2)
```




